### ISSUE TITLE
aliveRef.current?.getCaches()获取存在延迟

### ISSUE THREAD

**Issue by jinxiangqiang** [irychen/keepalive-for-react#11]
我需要获取缓存的数组生成tabs，但是直接获取会存在获取不及时的问题

**Comment by irychen** [comment]
可以在外部管理tabs，不需要通过aliveRef.current?.getCaches()获取缓存节点

可以参考 

- https://github.com/irychen/super-admin/blob/main/src/components/AdminPagesProvider/index.tsx
- https://github.com/irychen/super-admin

**Comment by jinxiangqiang** [comment]
好的
