### ISSUE TITLE
qiankun兼容

### ISSUE THREAD

**Issue by jinxiangqiang** [irychen/keepalive-for-react#14]
当{outlet}为qiankun子应用时，会导致跳转无法显示内容

**Comment by irychen** [comment]
可以给一个sandbox示例代码吗？

**Comment by jinxiangqiang** [comment]
我创建了个demo，dev分支，qiankun跳主应用页面后再进子应用缓存失效，且在子应用间切换只能渲染其中一个
https://github.com/jinxiangqiang/qiankunDemo/tree/dev

**Comment by irychen** [comment]
建议采用局部缓存方案，不要使用路由模式，没写过qiankun这个微前端框架，不太熟悉
