### ISSUE TITLE
The timer cannot be destroyed when refreshing the cache.

### ISSUE THREAD

**Issue by skyliwq** [irychen/keepalive-for-react#19]
我设置了定时器，在刷新 refresh 缓存后依旧执行，无法在
    useEffect(() => {
        return clearInterval(intervalRef.current)
    }, []) 销毁

I set a timer, and it continues to execute after refreshing the cache. It cannot be destroyed in 
    useEffect(() => {
        return clearInterval(intervalRef.current)
    }, []).

**Comment by irychen** [comment]
刷新之后useEffect重新执行设置新的定时器 
<img width="327" alt="image" src="https://github.com/user-attachments/assets/01e705f9-30ab-43f5-82ea-d28d2d30ba66">

```tsx
  useEffect(()=>{
      const interval = setInterval(()=>{
          console.log('interval');
      },1000);

      return ()=>{
          console.log('clear interval ---------------');
          clearInterval(interval);
      }
  },[])
```

考虑一下你的设置定时间逻辑，在什么情况下不用设置

**Comment by skyliwq** [comment]
谢谢，是我的疏忽
