### ISSUE TITLE
能帮忙看下用法吗， 使用了keepalive 没生效

### ISSUE THREAD

**Issue by mrliyaya** [irychen/keepalive-for-react#24]
https://codesandbox.io/p/sandbox/wpgxly

**Comment by condorheroblog** [comment]
KeepAlive 组件只能包裹路由的 outlet，其他的组件放在 KeepAlive 外面。

对于你的用例，请使用 Home 包裹 KeepAlive。

**Comment by mrliyaya** [comment]
> ```tsx
> export default function CacheLayout() {
>   const outlet = useOutlet();
>   const location = useLocation();
>   const cacheKey = useMemo(() => {
>     return location.pathname + location.search;
>   }, [location]);
> 
>   return (
>     <div>
>       <KeepAlive activeName={cacheKey} max={10} strategy={"LRU"}>
>          {outlet} 
>       </KeepAlive>
>     </div>
>   );
> }
> ```

可以使用children 属性这样子写吗 ？
```tsx
export default function CacheLayout(props) {
  const location = useLocation();
  const cacheKey = useMemo(() => {
    return location.pathname + location.search;
  }, [location]);

  return (
    <div>
      <KeepAlive activeName={cacheKey} max={10} strategy={"LRU"}>
         {props.children} 
      </KeepAlive>
    </div>
  );
}
```

**Comment by irychen** [comment]
keepalive 必须和 outlet在一起
