### ISSUE TITLE
[Feature Request] Enhance the capabilities of KeepAliveContext

### ISSUE THREAD

**Issue by condorheroblog** [irychen/keepalive-for-react#25]
The properties and methods on the `KeepAliveRef` method should also be available on the `KeepAliveContext`.

The reason for this is that sub components can flexibly read and control the behavior of KeepAlive through the KeepAliveContext.

**Comment by condorheroblog** [comment]
Please let me explain the benefits of doing this.

For example, if I want to add a cache flag to the tab, I can directly call `getCaches` through KeepAliveContext in this component.

Some closing operations of the tab can also be easily obtained through KeepAliveContext.

In this way, my tab component does not need to exchange data with the outside world, everything is done internally.

<img width="810" alt="image" src="https://github.com/user-attachments/assets/18c62166-d1fd-40da-983d-cfc6f8a436e4">

**Comment by irychen** [comment]
It is not necessary to reference https://github.com/irychen/super-admin. Keepalive will automatically manage cached React nodes, so the important thing is to manage the tab's data, which is independent of the Keepalive cached nodes. Even manually removing cached nodes is not necessary

**Comment by irychen** [comment]
If you believe it is meaningful for your project, you can commit a pull request (PR). There is a good opportunity to refactor the useImperativeHandle code implementation because it contains redundant code in relation to the props of CacheComponent.

**Comment by irychen** [comment]
If you don't have spare time, perhaps I will add this feature next month
