### ISSUE TITLE
可以支持有的路由缓存，有的路由不缓存吗？

### ISSUE THREAD

**Issue by chenqiuling** [irychen/keepalive-for-react#29]

**Comment by codejumpy** [comment]
exclude include

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: chenqiuling ***@***.***>
发送时间: Thursday, October 24, 2024 5:10:42 PM
收件人: irychen/keepalive-for-react ***@***.***>
抄送: Subscribed ***@***.***>
主题: [irychen/keepalive-for-react] 可以支持有的路由缓存，有的路由不缓存吗？ (Issue #29)


―

**Comment by irychen** [comment]
exclude include
