### ISSUE TITLE
请问支持 umi4 吗

### ISSUE THREAD

**Issue by xiaoshengwpp** [irychen/keepalive-for-react#33]

**Comment by irychen** [comment]
路由重定向会出问题，会出现路由加载慢，因为是umi自己封装的路由，暂时无法解决，推荐还是使用react-router-dom，如果不涉及重定向，或者非路由的缓存可以使用。

**Comment by jinxiangqiang** [comment]
我就是umi4，估计也是这个原因导致内存下不去，我现在只能停留在2.0.18才正常，2.0.19以上切换缓存动画会闪2下，然后就内存吃的很多

**Comment by irychen** [comment]
> 我就是umi4，估计也是这个原因导致内存下不去，我现在只能停留在2.0.18才正常，2.0.19以上切换缓存动画会闪2下，然后就内存吃的很多

最新的版本有这个问题吗？

**Comment by jinxiangqiang** [comment]
> > 我就是umi4，估计也是这个原因导致内存下不去，我现在只能停留在2.0.18才正常，2.0.19以上切换缓存动画会闪2下，然后就内存吃的很多
> 
> 最新的版本有这个问题吗？从2.0.18 之后移除了useLayoutEffact hook ，很奇怪react-router-dom没有出现内存问题

是的，最新的3.0.2也是有内存暴涨的问题，但是2.0.18之前都没有问题

**Comment by irychen** [comment]
这样的话。下个小版本加个umi兼容的feature。

**Comment by irychen** [comment]
不过重定向那个问题是解决不了的，所以umi项目上尽量避免在keepalive路由里面触发重定向

**Comment by lynn1286** [comment]
umi max 有使用示例吗？
我在 app.tsx 的 rootContainer 内调用 useLocation 会导致错误：
<img width="1146" alt="image" src="https://github.com/user-attachments/assets/63140de2-65b2-4bc8-8bed-dc1fdb6df239" />

**Comment by irychen** [comment]
> umi max 有使用示例吗？
> 
> 我在 app.tsx 的 rootContainer 内调用 useLocation 会导致错误：
> 
> <img width="1146" alt="image" src="https://github.com/user-attachments/assets/63140de2-65b2-4bc8-8bed-dc1fdb6df239" />
> 
> 

因为你的uselocation使用没有在router的子组件内使用， 你这超出了上下文作用域

**Comment by jinxiangqiang** [comment]
useLocation必须在路由里，这里层级不对，有需要我觉得可以考虑用window.location

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月24日 17:14 |
| 收件人 | irychen/keepalive-for-react ***@***.***> |
| 抄送人 | 金相强 ***@***.***>,
Comment ***@***.***> |
| 主题 | Re: [irychen/keepalive-for-react] 请问支持 umi4 吗 (Issue #33) |

umi max 有使用示例吗？
我在 app.tsx 的 rootContainer 内调用 useLocation 会导致错误：
image.png (view on web)

**Comment by lynn1286** [comment]
阅读源码得以发现：


```


1. 工作流程：
    1.1 初始渲染：
          KeepAliveRouteOutlet 生成缓存 key
          KeepAlive 创建缓存节点
          CacheComponent 创建 DOM 容器并渲染内容
2. 路由切换：
    2.1 更新 activeCacheKey
           KeepAlive 更新缓存状态
           相关 CacheComponent 执行 DOM 操作
3. 缓存机制：
    3.1 组件实例保持在内存中（通过 createPortal）
          DOM 节点通过添加/移除控制显示
          状态在 React 内部保持
4. 生命周期：
    4.1 组件不会真正卸载
          useEffect 继续执行
          状态得以保留
          
          
```
第四点组件不会真正卸载，导致普通的 useEffect 如果依赖了 路由上的 query 参数，在组件离开的时候，由于路由上的 query 变化，导致内存中的组件依旧会触发 useEffect 内的逻辑，但是我的 include  并没有该路由，这种情况算不算是 bug ，虽然我知道可以通过 useEffectOnActive 来解决问题。

**Comment by irychen** [comment]
> 阅读源码得以发现：
> 
> 
> 
> 
> 
> ```
> 
> 
> 
> 
> 
> 1. 工作流程：
> 
>     1.1 初始渲染：
> 
>           KeepAliveRouteOutlet 生成缓存 key
> 
>           KeepAlive 创建缓存节点
> 
>           CacheComponent 创建 DOM 容器并渲染内容
> 
> 2. 路由切换：
> 
>     2.1 更新 activeCacheKey
> 
>            KeepAlive 更新缓存状态
> 
>            相关 CacheComponent 执行 DOM 操作
> 
> 3. 缓存机制：
> 
>     3.1 组件实例保持在内存中（通过 createPortal）
> 
>           DOM 节点通过添加/移除控制显示
> 
>           状态在 React 内部保持
> 
> 4. 生命周期：
> 
>     4.1 组件不会真正卸载
> 
>           useEffect 继续执行
> 
>           状态得以保留
> 
>           
> 
>           
> 
> ```
> 
> 第四点组件不会真正卸载，导致普通的 useEffect 如果依赖了 路由上的 query 参数，在组件离开的时候，由于路由上的 query 变化，导致内存中的组件依旧会触发 useEffect 内的逻辑，但是我的 include  并没有该路由，这种情况算不算是 bug ，虽然我知道可以通过 useEffectOnActive 来解决问题。
> 
> 

是这样的，所以在非激活状态下useEffect避免使用会变化的依赖

**Comment by jswangtao** [comment]
> umi max 有使用示例吗？ 我在 app.tsx 的 rootContainer 内调用 useLocation 会导致错误： <img alt="image" width="1146" src="https://private-user-images.githubusercontent.com/40122311/398375525-63140de2-65b2-4bc8-8bed-dc1fdb6df239.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzI0MzU5OTMsIm5iZiI6MTc3MjQzNTY5MywicGF0aCI6Ii80MDEyMjMxMS8zOTgzNzU1MjUtNjMxNDBkZTItNjViMi00YmM4LThiZWQtZGMxZmRiNmRmMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjAzMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwMzAyVDA3MTQ1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYzYzVkZWRhYTY5ODAyZTZiMzFhNDAzNDhhNTMwMTViOGMyZDlmMDkwNDhhODgzZGVmMzQ1ODhmYjk0MGRiZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pQRMmIVFJ1Q63bAfCdhGO3SW1r_fVwTxHElF5cd2XQQ">

我也遇到你这个问题，我的框架是vite然后自己搭的，我的原因是keepalive-for-react-router里面依赖了"react-router": ">=6.0.0"  , 但是react-router现在有V6和V7，两个版本现在一个主包是react-router-dom，他去依赖了react-router，V7则直接是react-router一个包，如果项目里面是V6，然后react-router-dom会依赖到react-router@6版本，这个仓库可能会下载到react-router@7版本，就会报这个错，就跟两个实例一样

**Comment by finedaybreak** [comment]
umi 应该是不支持的， umi 自己封装了一套东西，可能路由依赖包还是很老的版本，我之前试过，效果不佳。不建议使用哈
