### ISSUE TITLE
KeepAlive 包裹 @tanstack/react-router, Outlet 组件无效

### ISSUE THREAD

**Issue by yibird** [irychen/keepalive-for-react#35]
由于React-router 的 useNavigate 存在重复渲染的问题,会造成严重的性能问题,为此我迁移到了@tanstack/react-router,它只提供了 Outlet组件,没有提供useOutlet, 使用时出现 index.mjs:10  Uncaught TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

**Comment by irychen** [comment]
很遗憾，目前不支持这个路由库。

**Comment by yibird** [comment]
![image](https://github.com/user-attachments/assets/3f3e711d-b6e7-4be4-b7a2-be1efc3c4b15)
我看源码就这个库用到了 react-router-dom, 这里可以获取<Keepalive> 的子节点吗,避免使用react-router-dom的api

**Comment by irychen** [comment]
这个其实只是一个Keepalive的语法糖，实际只使用Keepalive组件即可，但遗憾的是没有useOutlet的话，我尝试了一下只对@tanstack/react-router的<Outlet/> 缓存的话是不生效的，与react-router-dom的<Outlet/>情况类似

**Comment by condorheroblog** [comment]
可以根据 Outlet 组件内部的逻辑自己封装一个 useOutlet 来使用：

https://github.com/TanStack/router/blob/35af575ab4c623556ecdb613ac1c85864f0c95d9/packages/react-router/src/Match.tsx#L254C1-L304C3

**Comment by yibird** [comment]
路由库不同,自定义useOutlet 真的有用吗?

**Comment by condorheroblog** [comment]
我没试过，理论是可以的，你可以实践下。

**Comment by yibird** [comment]
> 这个其实只是一个Keepalive的语法糖，实际只使用Keepalive组件即可，但遗憾的是没有useOutlet的话，我尝试了一下只对@tanstack/react-router的`<Outlet/>` 缓存的话是不生效的，与react-router-dom的`<Outlet/>`情况类似。

<Outlet/> 本质上也是一个ReactNode, 源码里面可以避免使用 react-router-dom 的useOutlet,而是直接缓存Keepalive的子节点

**Comment by irychen** [comment]
只用Keepalive这个组件就不会用到react-router-dom的api

**Comment by yibird** [comment]
> 只用Keepalive这个组件就不会用到react-router-dom的api

但是渲染有问题

**Comment by irychen** [comment]
这个问题得需要@tanstack/react-router支持useOutlet这个hook

**Comment by yibird** [comment]
> 这个问题得需要@tanstack/react-router支持useOutlet这个hook

如果直接获取Keepalive的子节点并缓存 那将支持任意场景 跟Vue的Keepalive一样

**Comment by irychen** [comment]
这个原因就是Outlet组件就算被缓存住但是它会根据路由自己更新自己，keepalive无法接管它的渲染逻辑。
