### ISSUE TITLE
表单页面缓存的时候，当页面先打开详情页面再打开新增页面的时候，新增页面会默认展示详情页面的数据

### ISSUE THREAD

**Issue by meicy** [irychen/keepalive-for-react#36]
1、使用版本：
"antd": "^5.20.0",
"keepalive-for-react": "^3.0.6",
"react-router": "^6.23.0",
"react-router-dom": "^6.22.3",

2、复现流程
有一个表单提交页面，先查看详情，然后再打开新增，会出现新增页面默认展示了详情页面的数据。

**Comment by irychen** [comment]
你是不是没有做路由区分  比如user?type=create是新增 user?type=view&id=123是查看呢

**Comment by irychen** [comment]
相同的url对应的缓存页面是同一个所以需要做一下区分
