### ISSUE TITLE
Does it support nextjs route cache?

### ISSUE THREAD

**Issue by luckyyaxianzhi** [irychen/keepalive-for-react#4]
![image](https://github.com/irychen/keepalive-for-react/assets/106720731/8ac2ab60-1a6b-4ee5-b88b-e3b3be2786a0)

实际并没有缓存

**Comment by irychen** [comment]
Currently, next.js routing is not supported.

**Comment by luckyyaxianzhi** [comment]
有什么好的方案吗

**Comment by irychen** [comment]
退而求其次，你可以把缓存做在页面内，而不是routing上。

**Comment by luckyyaxianzhi** [comment]
但是我路由也想变化，如何保证路由变化，而已经打开的画面，重新切回去，画面内容不变呢

**Comment by irychen** [comment]
可以考虑将页面数据缓存到localstorage里面

**Comment by luckyyaxianzhi** [comment]
关键打开的画面可能会很多，还有iframe的画面，感觉不太行，放到localstorage，使用Portal createPortal可能实现吗

**Comment by irychen** [comment]
确实是一个比较棘手的问题，目前这个项目还没考虑到实现支持ssr路由方案。

**Comment by luckyyaxianzhi** [comment]
其实我们在代码里面都写了'use client';
把组件变为了客户端组件了

**Comment by irychen** [comment]
但是nextjs的路由是不支持的

**Comment by luckyyaxianzhi** [comment]
> 但是nextjs的路由是不支持的

这个是什么意思？是当前库不支持？还是nextjs的app router 的问题？

**Comment by irychen** [comment]
当前库不支持nextjs的路由级别keepalive，只支持react-router-dom v6

**Comment by luckyyaxianzhi** [comment]
因为现在想做的就是menu菜单，点击一个菜单，显示一个tab，每个打开的tab切换，页面内容不重新加载，使用 之前打开过的，这个有什么方式吗？因为现在是app router,每次进入到layout的children都会变化，所以内容就变化了

**Comment by luckyyaxianzhi** [comment]
或者说，用你现在的原理，实现一下nextjs的app router?

**Comment by irychen** [comment]
或许你可以尝试一下Nextjs [Dynamic Routes](https://nextjs.org/docs/app/building-your-application/routing/dynamic-routes)

**Comment by luckyyaxianzhi** [comment]
但是那样就不会有多tabs了
其实就是想实现如下的效果，只不过这个是react + antd 的tab组件 实现了 keep-alive效果
https://admin.slashspaces.com/

**Comment by irychen** [comment]
测试了下可以实现

**Comment by luckyyaxianzhi** [comment]
如何实现，有代码吗？

**Comment by irychen** [comment]
![image](https://github.com/irychen/keepalive-for-react/assets/94026641/fd23bbe7-1327-4da0-a636-00096dd00fe6) 技术交流群
